name: Snake Generator

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day
  workflow_dispatch:     # Allows to run manually
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-grey-light.svg?color_snake=808080&color_dots=#ffffff,#c0c0c0,#a0a0a0,#808080,#606060
            dist/github-contribution-grid-snake-grey-dark.svg?color_snake=ffffff&color_dots=#151515,#c4c4c4,#909090,#606060,#303030

      - name: Deploy to GitHub Page
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
